# @package _global_

defaults:
  - override hydra/job_logging: custom
  - _self_

task_name: "cotracker"

tags: ["cotracker"]

# input folder containing data for inference
input_path: /home/local/USHERBROOKE/juda2901/dev/TEMP/first40/first40_dirs/img/
segmentation_path: /home/local/USHERBROOKE/juda2901/dev/TEMP/first40/first40_dirs/segmentation/

# output folder to save predictions
output_path: OUTOUT

save_as_gif: True

# passing checkpoint path is necessary for prediction
ckpt_path: /home/local/USHERBROOKE/juda2901/Téléchargements/cotracker_torchscript-20251021T174250Z-1-001/cotracker_torchscript/cotracker_predict_ts.pt

common_spacing: [0.37, 0.37, 1]

apply_eq_hist: False

pin_memory: True

num_workers: 12

hydra:
  output_subdir: null
  run:
    dir: .
  job_logging:
    disable_existing_loggers: true  # disables logging to hydra.log
  hydra_logging:
    disable_existing_loggers: true  # disables logging to hydra.log

